name: Update scene exceptions

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0,4,10,16 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.0a1
      - name: Run exception updater.
        run: |
          pip install poethepoet
          poetry install
          poe poetry_update
          poe run
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update scene exceptions

          branch: update-scene-exceptions
          commit_options: '--no-verify --signoff'

          status_options: '--untracked-files=no'
          
          # Optional commit user and author settings
          commit_user_name: miigotu
          commit_user_email: miigotu@gmail.com
          commit_author: miigotu <miigotu@gmail.com>
